services:
  db:
    image: postgres:16
    restart: on-failure:5
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grpc_server:
    image: andytakker/vtb-api-2024-grpc-server:latest
    ports:
      - "$APP_GRPC_PORT:$APP_GRPC_PORT"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_GRPC_HOST=$APP_GRPC_HOST
      - APP_GRPC_PORT=$APP_GRPC_PORT
      - APP_TLS_CERT_FILE_PATH=$APP_TLS_CERT_FILE_PATH
      - APP_TLS_KEY_FILE_PATH=$APP_TLS_KEY_FILE_PATH
      - APP_TLS_CA_FILE_PATH=$APP_TLS_CA_FILE_PATH

  grpc_client: 
    image: andytakker/vtb-api-2024-grpc-client:latest
    ports:
      - "$APP_CLIENT_PORT:$APP_CLIENT_PORT"
    depends_on:
      - grpc_server
    environment:
      - APP_CLIENT_PORT=$APP_CLIENT_PORT
volumes:
  postgres_data:
